### ISSUE TITLE
Add some examples that use floating-point operations

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/copilot-verifier#3]
We should demonstrate the `copilot-verifier` is capable of handling of specifications that make use of floating-point operations. A good first milestone is the [`Heater` example](https://github.com/Copilot-Language/copilot/blob/11ab89fbb839a99aa021f458567c7d4b7ad0c745/copilot/examples/Heater.hs) from the `copilot` repo (not to be confused with `copilot-verifier`'s own `Heater` example, which avoids the use of floating-point). At the moment, if you try running `copilot-verifier` on this `Heater` example, it will fail to prove these goals:

<details>

```
=====
== Running the HeaterCelsius example...
=====

Generated "results/heaterCelsius/heaterCelsius.c"
Compiled heaterCelsius into results/heaterCelsius/crux~heaterCelsius.bc
Translated bitcode into Crucible
Generating proof state data
Computing initial state verification conditions
Proving initial state verification conditions
All obligations proved by concrete simplification
Computing step bisimulation verification conditions
Proving step bisimulation verification conditions
Proved 0 of 4 total goals
[Crux] Found counterexample for verification goal
[Crux]   results/heaterCelsius/heaterCelsius.c:30:6: error: in step
[Crux]   Mismatch between Copilot value and crucible value
[Crux]   XFloat let -- :1:0
[Crux]       v15 = floatMul RNE (bvToFloat RNE ctemperature_r0@13:bv) 0x0.969697
[Crux]    in floatSub RNE v15 0x32
[Crux]   FloatRepr SingleFloatRepr
[Crux] 
[Crux] 
[Crux] Found counterexample for verification goal
[Crux]   results/heaterCelsius/heaterCelsius.c:33:6: error: in step
[Crux]   Mismatch between Copilot value and crucible value
[Crux]   XFloat let -- :1:0
[Crux]       v15 = floatMul RNE (bvToFloat RNE ctemperature_r0@13:bv) 0x0.969697
[Crux]    in floatSub RNE v15 0x32
[Crux]   FloatRepr SingleFloatRepr
[Crux] 
[Crux] 
[Crux] Found counterexample for verification goal
[Crux]   internal: error: in <>
[Crux]   Trigger guard equality condition: "heaton"
[Crux]   Details:
[Crux]     let -- :1:0
[Crux]         v15 = floatMul RNE (bvToFloat RNE ctemperature_r0@13:bv) 0x0.969697
[Crux]      in not (floatLt (floatSub RNE v15 0x32) 0x12)
[Crux] 
[Crux] Found counterexample for verification goal
[Crux]   internal: error: in <>
[Crux]   Trigger guard equality condition: "heatoff"
[Crux]   Details:
[Crux]     let -- :1:0
[Crux]         v15 = floatMul RNE (bvToFloat RNE ctemperature_r0@13:bv) 0x0.969697
[Crux]      in not (floatLt 0x15 (floatSub RNE v15 0x32))
```
</details>

If we get that working, we can become more ambitious and try to verify examples that use transcendental functions, such as [this `Trig` example](https://github.com/Copilot-Language/copilot/blob/11ab89fbb839a99aa021f458567c7d4b7ad0c745/copilot-theorem/examples/Trig.hs). That will first require incorporating GaloisInc/what4#160 into `crucible-llvm` and overriding the necessary functions in LLVM. I have a WIP branch for this [here](https://github.com/GaloisInc/crucible/tree/special-functions).

**Comment by robdockins** [comment]
The well-clear violation example (WCV) would also be good; it doesn't use any special functions I think, so it should be easier to get going than `Trig`.

**Comment by RyanGlScott** [comment]
The upstream `copilot` repo has recently added support for the following in `copilot-c99`:

* `atan2` (Copilot-Language/copilot@6c11ea09dedb21d33bf3cce9af5db3be0629d9f9)
* `ceil` (Copilot-Language/copilot@7d0e675d847789d38feeec6619bee607ad02cbf5)
* `floor` (Copilot-Language/copilot@6a0d260b769c9e895be33e94380a14ad4ffd25ea)

**Comment by RyanGlScott** [comment]
#5 adds a very realistic floating-point example to the test suite, which I think is a nice way to wrap a bow on this issue. The only remaining task is ensuring that all floating-point operations have test cases (see the third checkbox in https://github.com/GaloisInc/copilot-verifier/issues/3#issuecomment-944643076), but I'll do that task as part of #13.
